name: My first workflow

on: push
jobs: 
    first-job:
        runs-on: ubuntu-Latest
        steps:
            - name: Welcome to my first workflow
              run: echo "Hello, world! This is my first workflow."
            - name: List all files
              run: ls -la
            - name: Read a file
              run: cat README.md
            
   